ctrl_n_shortcuts = false
search_mode = "skim"
filter_mode = "global"
style = "compact"
auto_sync = true
case_sensitive = false
tore_success_only = true
sync_address = "https://atuin.lan.becker.kiwi"
sync_frequency = "6h"
history_format = "plain"
secrets_filter = true
show_preview = true
show_help = false
inline_height = 20
word_jump_mode = "emacs"
ignored_commands = [
  "cd",
  "zoxide",
  "ls",
  "eza",
  "nvim",
  "ydl",
  "ll",
  "la",
  "sync"
]
