---
firefox_addons:
  - ublock-origin
  - bitwarden-password-manager
  - sponsorblock
  - multi-account-containers
  - violentmonkey
  - return-youtube-dislikes
  - clearurls
  - buster-captcha-solver
  - fastforwardteam
  - absolute-enable-right-click
  - i-dont-care-about-cookies
  - redirector
  - styl-us
  - surfingkeys_ff
  - view-page-archive
  - ambient-theme-by-site-colour
