---
packages:
  - git
  - git-lfs
  - chezmoi
  - nmon
  - bottom
  - socat
  - bat
  - bat-extras
  - direnv
  - ansible
  - ripgrep
  - gzip
  - gettext
  - pyenv
  - p7zip
  - fastfetch
  - gzip
  - fzf
  # fzf-tmux is included with fzf package
  - fd
  - ansible-lint
  - tealdeer
  - eza
  - strace
  - yazi
  - sshpass
  - gopass
  - atuin
  - zip
  - unrar
  - btop
  - shellcheck
  - pwgen
  - gcc
  - make
  - openssl
  - tcpdump
  - nmap
  - zoxide
  - jq
  - yq
  - inetutils
  - net-tools
  - gcc
  - bind
  - starship
  - openbsd-netcat
  - hyperfine
  - nodejs
  - curl
  - pandoc
  - tmux
