---
packages:
  - git
  - git-lfs
  - chezmoi
  - nmon
  - bottom
  - socat
  - bat
  - bat-extras
  - direnv
  - ansible
  - ripgrep
  - gzip
  - gettext-tools
  - pyenv
  - 7zip
  - fastfetch
  - gzip
  - fzf
  - fzf-tmux
  - fd
  - ansible-lint
  - tealdeer
  - eza
  - strace
  - yazi
  - sshpass
  - gopass
  - atuin
  - zip
  - unrar
  - btop
  - ShellCheck
  - pwgen
  - gcc
  - make
  - openssl
  - tcpdump
  - nmap
  - zoxide
  - jq
  - yq
  - telnet
  - net-tools
  - gcc-c++
  - bind-utils
  - starship
  - netcat-openbsd
  - hyperfine
  - nodejs
  - curl
  - pandoc
  - tmux
