add_newline = false
format = """$directory$git_branch$git_status$ruby$hostname$python$character"""
command_timeout = 200

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â­](bold red)"
vimcmd_symbol = "[â°](bold cyan)"

[directory]
truncation_length = 3
truncation_symbol = 'â€¦/'
truncate_to_repo	= true

[directory.substitutions]
"Documents" = "ïœ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Videos" = "ï³œ"
"Pictures" = "ï€¾ "
"Projects" = "ï£ª"
".dotfiles" = "ï‘„"

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
ignore_branches = ['master', 'main']

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = ''


[ruby]
format = '[$symbol$version(:$gemset )]($style)' 
symbol = "â– "
style = "bold blue"


[python]
format = '[$symbol$version( ğŸ $virtualenv)]($style)' 
symbol = "ğŸ "
style = "bold yellow"

[hostname]
ssh_only = true
trim_at = "."
format = '[$ssh_symbol]($style)'
ssh_symbol = "â¯"
style = 'bold green'


