[env]
KUBECONFIG = "{{ exec(command='cd ' ~ env.HOME ~ ' && KUBECONFIG=$(printf \"%s:\" .kube/*.yaml | sed \"s/:$//\") kubectl config view --flatten --raw > .kube/config && echo ' ~ env.HOME ~ '/.kube/config') }}"

[settings]
experimental = true

[tools]
# Languages
bun = "latest"
deno = "latest"
go = "latest"
java = "lts"
node = "lts"
python = "latest"
rust = "latest"
zig = "latest"

# Kubernetes
helm = "latest"
kubectl = "latest"
kustomize = "latest"
k9s = "latest"
kubectx = "latest"
kubens = "latest"
stern = "latest"
k3s = "latest"
flux2 = "latest"
cilium-cli = "latest"
argocd = "latest"
kubeseal = "latest"
krew = "latest"

# IaC / Cloud
opentofu = "latest"
vault = "latest"
ansible = "latest"
packer = "latest"
age = "latest"
gcloud = "latest"
azure-cli = "latest"

# Dev tools
direnv = "latest"
github-cli = "latest"
yarn = "latest"
opencode = "latest"
jq = "latest"
yq = "latest"
shellcheck = "latest"
shfmt = "latest"
pipx = "latest"
pipenv = "latest"
cookiecutter = "latest"
yt-dlp = "latest"
actionlint = "latest"
hugo = "latest"
