---
fonts:
  - ttf-font-awesome
  - ttf-roboto
  - ttf-droid

packages:
  - podman
  - podman-docker
  # appimaged not available in official repos
  - hplip
  - podman-compose
  - networkmanager
  - networkmanager-vpnc
  - networkmanager-openconnect
  - networkmanager-openvpn
  - nm-connection-editor
  - mpv
  - xdg-user-dirs
  - xdg-utils
  - ffmpeg
  - wl-clipboard
  - rust
  - flatpak
  - android-tools
  - yt-dlp
  - syncthing

flatpak:
  - org.jdownloader.JDownloader
  - us.zoom.Zoom
  - org.localsend.localsend_app
  - org.telegram.desktop
